version: 2
jobs:
  build:
    docker:
      - image: microsoft/azure-cli:latest
    steps:
      - checkout

      - setup_remote_docker:   
          docker_layer_caching: true 

      # build and push Docker image
      - run:
          name: Build docker image
          command: |
            TAG=0.$CIRCLE_BUILD_NUM
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker-compose -f docker-compose.yml build
              docker tag url2pdfapi:latest baron123.azurecr.io/number-word/url2pdfapi:$1
              docker login baron123.azurecr.io -u $DOCKER_USER -p $DOCKER_PASS        
              docker push baron123.azurecr.io/number-word/url2pdfapi
            fi