version: 2
jobs:
  build:
    docker:
      - image: microsoft/azure-cli:latest
    steps:
      - checkout
      - run:
          name: Install docker compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-$(uname -s)-$(uname -m) -o ~/docker-compose
            chmod +x ~/docker-compose

      - setup_remote_docker:   
          docker_layer_caching: true 

      # build and push Docker image
      - run:
          name: Build docker image
          command: |
            TAG=0.$CIRCLE_BUILD_NUM
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./deploy/build-image.sh
              ./deploy/push-image.sh $TAG
            fi