version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5-node
    steps:
      - checkout

      - setup_remote_docker:   
          docker_layer_caching: true 

      # build and push Docker image
      - run:
          name: Build docker image
          command: |
            TAG=0.$CIRCLE_BUILD_NUM
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./builds/build-image.sh
              ./builds/push-image.sh $TAG
            fi

  deploy:
    docker:
      - image: microsoft/azure-cli:latest
    steps:
      - checkout

      # build and push Docker image
      - run:
          name: Deploy to ACI
          command: |
            TAG=0.$CIRCLE_BUILD_NUM
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./deploy/config-cli.sh
              ./deploy/aci-deploy.sh $TAG
            fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
